name: Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build_OSX:
    runs-on: macos-latest
    env: 
      PRurl: https://github.com/PCX-LK/animbean
      PRname: animbean
    steps:
      - name: os fetch
        run: |
          brew install neofetch
          neofetch
      - name: clone
        run: |
          git clone --recursive $PRurl
      - name: Nim
        run: |
          brew install nim
      - name: Set Up
        run: |
          export PATH="~/.nimble/bin:$PATH"
          source ~/.bashrc
          cd $PRname
          nimble install -y -d
      - name: Build Mac
        run: |
          export PATH="~/.nimble/bin:$PATH"
          source ~/.bashrc
          cd $PRname
          nimble deploy
      - name: Upload to Build branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: Build
          build_dir: ./$PRname/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
