name: Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: clone
        run: |
          git clone https://github.com/Anuken/animdustry
      - name: Nim
        run: |
          berw install nim
