name: Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: clone
        run: |
          git clone https://github.com/Anuken/animdustry
      - name: Brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Nim
        run: |
          brew install nim
